language: node_js
node_js:
- '8'
addons:
  ssh_known_hosts: 47.93.35.195
before_install:
- openssl aes-256-cbc -K $encrypted_d46434b71a4b_key -iv $encrypted_d46434b71a4b_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- openssl aes-256-cbc -K $encrypted_d46434b71a4b_key -iv $encrypted_d46434b71a4b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
before_script:
- nvm install 8.10 && nvm use 8.10
- npm install
- npm install -g @commitlint/travis-cli
- npm install -g apollo
after_script:
- apollo schema:publish  --key="service:cd-graphql-1493:tA5PTDJyXpHA-L9wovqXeg"  --endpoint="http://du0o.com:4000/graphql"
  --tag=beta
after_success:
- ssh root@47.93.35.195 "./your-shell-script"
